import type { Driver, DriverAvailability } from '@/types/driver';

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'DRV-00293',
    name: 'Marcus Rivera',
    phone: '+1 (312) 555-0192',
    email: 'm.rivera@swifthaul.com',
    vehicle: 'Ford Transit',
    vehiclePlate: 'IL-294-XZ3',
    availability: 'AVAILABLE',
    currentLoad: 0,
    maxLoad: 3,
    completedToday: 12,
    avgDeliveryTime: '24 min',
    avatarInitials: 'MR',
    rating: 4.9,
    totalDeliveries: 847,
  },
  {
    id: 'DRV-00104',
    name: 'Elena Walsh',
    phone: '+1 (312) 555-0821',
    email: 'e.walsh@swifthaul.com',
    vehicle: 'Mercedes Sprinter',
    vehiclePlate: 'CH-882-QQ1',
    availability: 'AVAILABLE',
    currentLoad: 1,
    maxLoad: 4,
    completedToday: 15,
    avgDeliveryTime: '21 min',
    avatarInitials: 'EW',
    rating: 4.8,
    totalDeliveries: 1248,
  },
  {
    id: 'DRV-00441',
    name: 'Tyrell King',
    phone: '+1 (312) 555-1200',
    email: 't.king@swifthaul.com',
    vehicle: 'Ram ProMaster',
    vehiclePlate: 'NY-182-PP4',
    availability: 'BUSY',
    currentLoad: 3,
    maxLoad: 3,
    completedToday: 8,
    avgDeliveryTime: '32 min',
    avatarInitials: 'TK',
    rating: 4.6,
    totalDeliveries: 512,
  },
  {
    id: 'DRV-00382',
    name: 'Sarah Jenkins',
    phone: '+1 (312) 555-9082',
    email: 's.jenkins@swifthaul.com',
    vehicle: 'Nissan NV',
    vehiclePlate: 'FL-445-XX9',
    availability: 'BUSY',
    currentLoad: 2,
    maxLoad: 3,
    completedToday: 10,
    avgDeliveryTime: '28 min',
    avatarInitials: 'SJ',
    rating: 4.9,
    totalDeliveries: 934,
  },
  {
    id: 'DRV-00084',
    name: 'David Lopez',
    phone: '+1 (312) 555-2231',
    email: 'd.lopez@swifthaul.com',
    vehicle: 'Ford Transit',
    vehiclePlate: 'IL-112-5B9',
    availability: 'OFFLINE',
    currentLoad: 0,
    maxLoad: 3,
    completedToday: 18,
    avgDeliveryTime: '19 min',
    avatarInitials: 'DL',
    rating: 4.7,
    totalDeliveries: 2103,
  },
  {
    id: 'DRV-00192',
    name: 'Mia Chen',
    phone: '+1 (312) 555-8833',
    email: 'm.chen@swifthaul.com',
    vehicle: 'Mercedes Sprinter',
    vehiclePlate: 'WA-992-HM8',
    availability: 'OFFLINE',
    currentLoad: 0,
    maxLoad: 4,
    completedToday: 0,
    avgDeliveryTime: 'N/A',
    avatarInitials: 'MC',
    rating: 4.5,
    totalDeliveries: 321,
  },
  {
    id: 'DRV-00517',
    name: 'James Okafor',
    phone: '+1 (312) 555-3341',
    email: 'j.okafor@swifthaul.com',
    vehicle: 'Chevrolet Express',
    vehiclePlate: 'OH-773-KK2',
    availability: 'AVAILABLE',
    currentLoad: 2,
    maxLoad: 4,
    completedToday: 9,
    avgDeliveryTime: '26 min',
    avatarInitials: 'JO',
    rating: 4.7,
    totalDeliveries: 688,
  },
  {
    id: 'DRV-00609',
    name: 'Priya Sharma',
    phone: '+1 (312) 555-6612',
    email: 'p.sharma@swifthaul.com',
    vehicle: 'Ford Transit',
    vehiclePlate: 'CA-551-ZZ8',
    availability: 'BUSY',
    currentLoad: 3,
    maxLoad: 3,
    completedToday: 11,
    avgDeliveryTime: '22 min',
    avatarInitials: 'PS',
    rating: 4.8,
    totalDeliveries: 456,
  },
  {
    id: 'DRV-00712',
    name: 'Andre Mitchell',
    phone: '+1 (312) 555-4490',
    email: 'a.mitchell@swifthaul.com',
    vehicle: 'Ram ProMaster',
    vehiclePlate: 'TX-221-QR7',
    availability: 'AVAILABLE',
    currentLoad: 1,
    maxLoad: 3,
    completedToday: 7,
    avgDeliveryTime: '30 min',
    avatarInitials: 'AM',
    rating: 4.6,
    totalDeliveries: 290,
  },
  {
    id: 'DRV-00801',
    name: 'Fatima Hassan',
    phone: '+1 (312) 555-7721',
    email: 'f.hassan@swifthaul.com',
    vehicle: 'Mercedes Sprinter',
    vehiclePlate: 'GA-334-PP9',
    availability: 'OFFLINE',
    currentLoad: 0,
    maxLoad: 4,
    completedToday: 5,
    avgDeliveryTime: '27 min',
    avatarInitials: 'FH',
    rating: 4.9,
    totalDeliveries: 1102,
  },
];

export const AVAILABILITY_STYLES: Record<DriverAvailability, { dot: string; badge: string; label: string }> = {
  AVAILABLE: {
    dot: 'bg-success',
    badge: 'bg-success/10 text-success',
    label: 'Available',
  },
  BUSY: {
    dot: 'bg-warning',
    badge: 'bg-warning/10 text-warning',
    label: 'Busy',
  },
  OFFLINE: {
    dot: 'bg-border-strong',
    badge: 'bg-surface-elevated text-text-muted',
    label: 'Offline',
  },
};
