import type { DriverAlert } from '@/types/driver-pages';
import type { NotificationType } from '@/types/notification';

export const MOCK_DRIVER_ALERTS: DriverAlert[] = [
  {
    id: 'alert-1',
    type: 'ORDER_ASSIGNED',
    title: 'New Order Assigned',
    message: 'Order SH-900f21a2 has been assigned to you. Pick up from Liberty Ave Downtown Plaza by 4:00 PM.',
    time: '10 min ago',
    isRead: false,
  },
  {
    id: 'alert-2',
    type: 'DELIVERY_FAILED',
    title: 'Delivery Failed',
    message: 'Order SH-231a44p9 failed: recipient not available at delivery address.',
    time: '22 min ago',
    isRead: false,
  },
  {
    id: 'alert-3',
    type: 'STATUS_CHANGED',
    title: 'Status Updated',
    message: 'Order SH-a8f3r7v2 moved to IN TRANSIT.',
    time: '1 hr ago',
    isRead: true,
  },
  {
    id: 'alert-4',
    type: 'SYSTEM_MAINTENANCE',
    title: 'Scheduled Maintenance',
    message: 'System maintenance is planned tonight at 2:00 AM. Tracking may be briefly unavailable.',
    time: '2 hr ago',
    isRead: true,
  },
  {
    id: 'alert-5',
    type: 'SHIPMENT_UPDATE',
    title: 'Shipment Update',
    message: 'Bulk shipment SH-782x90k1 has arrived at the downtown hub.',
    time: '3 hr ago',
    isRead: true,
  },
  {
    id: 'alert-6',
    type: 'ROUTE_UPDATED',
    title: 'Route Updated',
    message: "Your route order has been optimized to reduce travel time.",
    time: 'Yesterday',
    isRead: true,
  },
  {
    id: 'alert-7',
    type: 'DELIVERY_COMPLETED',
    title: 'Delivery Completed',
    message: 'Order SH-114z09q5 was delivered successfully.',
    time: 'Yesterday',
    isRead: true,
  },
  {
    id: 'alert-8',
    type: 'DRIVER_ONLINE',
    title: 'Driver Online',
    message: 'You are now marked online and available for assignments.',
    time: '2 days ago',
    isRead: true,
  },
  {
    id: 'alert-9',
    type: 'DRIVER_OFFLINE',
    title: 'Driver Offline',
    message: 'You have been marked offline. Switch to available to receive new assignments.',
    time: '3 days ago',
    isRead: true,
  },
  {
    id: 'alert-10',
    type: 'SYSTEM_UPDATE',
    title: 'System Update',
    message: 'A new app update is available with improved route calculations.',
    time: '3 days ago',
    isRead: true,
  },
  {
    id: 'alert-11',
    type: 'ORDER_ASSIGNED',
    title: 'New Order Assigned',
    message: 'Order SH-441k77m3 has been assigned to you. Pick up from North Shore Warehouse by 9:30 AM.',
    time: '4 days ago',
    isRead: true,
  },
  {
    id: 'alert-12',
    type: 'STATUS_CHANGED',
    title: 'Status Updated',
    message: 'Order SH-774g33k8 moved to OUT FOR DELIVERY.',
    time: '4 days ago',
    isRead: true,
  },
  {
    id: 'alert-13',
    type: 'DELIVERY_COMPLETED',
    title: 'Delivery Completed',
    message: 'Order SH-754w63c1 was delivered successfully.',
    time: '5 days ago',
    isRead: true,
  },
  {
    id: 'alert-14',
    type: 'SHIPMENT_UPDATE',
    title: 'Shipment Update',
    message: 'Bulk shipment SH-900f21a2 departed from City Logistics Hub.',
    time: '6 days ago',
    isRead: true,
  },
];

export const ALERT_TYPE_STYLES: Record<NotificationType, { bg: string; text: string; dot: string; label: string }> = {
  ORDER_ASSIGNED:     { bg: 'bg-info/10',          text: 'text-info',        dot: 'bg-info',        label: 'Assigned' },
  STATUS_CHANGED:     { bg: 'bg-warning/10',       text: 'text-warning',     dot: 'bg-warning',     label: 'Updated'  },
  DELIVERY_COMPLETED: { bg: 'bg-success/10',       text: 'text-success',     dot: 'bg-success',     label: 'Delivered' },
  DELIVERY_FAILED:    { bg: 'bg-error/10',         text: 'text-error',       dot: 'bg-error',       label: 'Failed'   },
  DRIVER_ONLINE:      { bg: 'bg-success/10',       text: 'text-success',     dot: 'bg-success',     label: 'Online'   },
  DRIVER_OFFLINE:     { bg: 'bg-surface-elevated', text: 'text-text-muted',  dot: 'bg-text-muted',  label: 'Offline'  },
  SYSTEM_MAINTENANCE: { bg: 'bg-purple-50',        text: 'text-purple-600',  dot: 'bg-purple-500',  label: 'System'   },
  SYSTEM_UPDATE:      { bg: 'bg-surface-elevated', text: 'text-text-muted',  dot: 'bg-text-muted',  label: 'System'   },
  SHIPMENT_UPDATE:    { bg: 'bg-primary-subtle',   text: 'text-primary-light', dot: 'bg-primary-light', label: 'Shipment' },
  ROUTE_UPDATED:      { bg: 'bg-info/10',          text: 'text-info',        dot: 'bg-info',        label: 'Route'    },
};
