import type { DriverAlert, DriverAlertType } from '@/types/driver-pages';

export const MOCK_DRIVER_ALERTS: DriverAlert[] = [
  {
    id: 'alert-1',
    type: 'ORDER_ASSIGNED',
    title: 'New Order Assigned',
    message: 'Order SH-900f21a2 has been assigned to you. Pick up from Liberty Ave Downtown Plaza by 4:00 PM.',
    time: '10 min ago',
    isRead: false,
  },
  {
    id: 'alert-2',
    type: 'URGENT',
    title: 'Priority Delivery',
    message: 'Order SH-231a44p9 is marked EXPRESS priority. Customer is waiting — please pick up ASAP.',
    time: '22 min ago',
    isRead: false,
  },
  {
    id: 'alert-3',
    type: 'ORDER_UPDATED',
    title: 'Delivery Address Updated',
    message: 'Recipient updated their address for SH-a8f3r7v2. New address: 842 North Michigan Ave, Suite 1205.',
    time: '1 hr ago',
    isRead: true,
  },
  {
    id: 'alert-4',
    type: 'SCHEDULE_CHANGE',
    title: 'Shift Reminder',
    message: 'Your afternoon shift starts in 30 minutes. You have 3 deliveries queued for 2:00 PM – 5:00 PM.',
    time: '2 hr ago',
    isRead: true,
  },
  {
    id: 'alert-5',
    type: 'ORDER_ASSIGNED',
    title: 'Order Accepted',
    message: 'You accepted order SH-782x90k1. Pick up from TechHub Distribution Center, Commerce Way.',
    time: '3 hr ago',
    isRead: true,
  },
  {
    id: 'alert-6',
    type: 'SYSTEM',
    title: 'Route Optimized',
    message: "We've updated your route order for maximum efficiency. 3 upcoming stops reordered.",
    time: 'Yesterday',
    isRead: true,
  },
  {
    id: 'alert-7',
    type: 'ORDER_UPDATED',
    title: 'Delivery Rescheduled',
    message: 'Order SH-114z09q5 has been rescheduled to tomorrow, 10:00 AM – 12:00 PM by dispatch.',
    time: 'Yesterday',
    isRead: true,
  },
  {
    id: 'alert-8',
    type: 'SYSTEM',
    title: 'Weekly Summary',
    message: 'Great work this week! You completed 23 deliveries with a 96% on-time rate. Keep it up!',
    time: '2 days ago',
    isRead: true,
  },
  {
    id: 'alert-9',
    type: 'ORDER_ASSIGNED',
    title: 'New Order Assigned',
    message: 'Order SH-441k77m3 has been assigned to you. Pick up from North Shore Warehouse by 9:30 AM.',
    time: '3 days ago',
    isRead: true,
  },
  {
    id: 'alert-10',
    type: 'URGENT',
    title: 'Failed Delivery Follow-up',
    message: 'Order SH-391b55n1 could not be delivered. Dispatch has rescheduled for tomorrow morning.',
    time: '3 days ago',
    isRead: true,
  },
  {
    id: 'alert-11',
    type: 'SCHEDULE_CHANGE',
    title: 'Tomorrow Schedule Ready',
    message: 'Your route for tomorrow has been generated: 5 stops, starting at 8:00 AM from City Logistics Hub.',
    time: '4 days ago',
    isRead: true,
  },
  {
    id: 'alert-12',
    type: 'ORDER_UPDATED',
    title: 'Recipient Phone Updated',
    message: 'Contact number changed for SH-774g33k8. New number on file: +1 (312) 555-0918.',
    time: '4 days ago',
    isRead: true,
  },
  {
    id: 'alert-13',
    type: 'SYSTEM',
    title: 'App Update Available',
    message: 'SwiftHaul driver app v2.1 is available. Update for improved route calculations and faster load times.',
    time: '5 days ago',
    isRead: true,
  },
  {
    id: 'alert-14',
    type: 'ORDER_ASSIGNED',
    title: 'Batch Route Assigned',
    message: '3 orders have been assigned as a batch route. Total distance: 11.4 mi. Pick up window: 7:00 – 9:00 AM.',
    time: '6 days ago',
    isRead: true,
  },
];

export const ALERT_TYPE_STYLES: Record<DriverAlertType, { bg: string; text: string; dot: string; label: string }> = {
  ORDER_ASSIGNED:  { bg: 'bg-info/10',          text: 'text-info',        dot: 'bg-info',        label: 'Assigned' },
  ORDER_UPDATED:   { bg: 'bg-warning/10',        text: 'text-warning',     dot: 'bg-warning',     label: 'Updated'  },
  SCHEDULE_CHANGE: { bg: 'bg-purple-50',         text: 'text-purple-600',  dot: 'bg-purple-500',  label: 'Schedule' },
  SYSTEM:          { bg: 'bg-surface-elevated',  text: 'text-text-muted',  dot: 'bg-text-muted',  label: 'System'   },
  URGENT:          { bg: 'bg-error/10',          text: 'text-error',       dot: 'bg-error',       label: 'Urgent'   },
};
