import type { AppNotification } from '@/types/notification';

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n-001',
    type: 'ORDER_ASSIGNED',
    title: 'Order Assigned',
    message: 'Order SH-8291X has been successfully assigned to driver Marcus Wright.',
    orderRef: 'SH-8291X',
    boldRef: 'Marcus Wright',
    isRead: false,
    timestamp: '2 minutes ago',
  },
  {
    id: 'n-002',
    type: 'DELIVERY_FAILED',
    title: 'Delivery Failed',
    message: 'Delivery for SH-1104Z failed due to: Recipient not available.',
    orderRef: 'SH-1104Z',
    errorRef: 'Recipient not available.',
    isRead: false,
    timestamp: '15 minutes ago',
  },
  {
    id: 'n-003',
    type: 'DELIVERY_COMPLETED',
    title: 'Delivery Completed',
    message: 'Package SH-9902A was delivered successfully to Acme Corp HQ.',
    orderRef: 'SH-9902A',
    isRead: true,
    timestamp: '1 hour ago',
  },
  {
    id: 'n-004',
    type: 'DRIVER_ONLINE',
    title: 'New Driver Online',
    message: 'Driver Sarah Jenkins is now online and available for assignments in North Sector.',
    boldRef: 'Sarah Jenkins',
    isRead: true,
    timestamp: '3 hours ago',
  },
  {
    id: 'n-005',
    type: 'SYSTEM_MAINTENANCE',
    title: 'System Maintenance',
    message: 'Scheduled maintenance completed. All real-time tracking features are operating at 100% capacity.',
    isRead: true,
    timestamp: 'Yesterday, 10:45 PM',
  },
  {
    id: 'n-006',
    type: 'ORDER_ASSIGNED',
    title: 'Order Assigned',
    message: 'Order SH-a8f3x9k2 has been assigned to driver John Makinde.',
    orderRef: 'SH-a8f3x9k2',
    boldRef: 'John Makinde',
    isRead: false,
    timestamp: '4 hours ago',
  },
  {
    id: 'n-007',
    type: 'DELIVERY_COMPLETED',
    title: 'Delivery Completed',
    message: 'Order SH-b7e2m4p1 was delivered successfully and signed.',
    orderRef: 'SH-b7e2m4p1',
    isRead: true,
    timestamp: '5 hours ago',
  },
  {
    id: 'n-008',
    type: 'DELIVERY_FAILED',
    title: 'Delivery Failed',
    message: 'Order SH-c9d1k6n3 failed: Recipient not home at destination.',
    orderRef: 'SH-c9d1k6n3',
    errorRef: 'Recipient not home at destination.',
    isRead: false,
    timestamp: '6 hours ago',
  },
  {
    id: 'n-009',
    type: 'ROUTE_UPDATED',
    title: 'Route Updated',
    message: 'Driver adjusted route for SH-x1y2z3 to avoid traffic on I-94.',
    orderRef: 'SH-x1y2z3',
    isRead: true,
    timestamp: '7 hours ago',
  },
  {
    id: 'n-010',
    type: 'SHIPMENT_UPDATE',
    title: 'Shipment Update',
    message: 'Bulk shipment SH-z2q9v5l4 has arrived at Hub Lagos North.',
    orderRef: 'SH-z2q9v5l4',
    isRead: true,
    timestamp: 'Yesterday',
  },
  {
    id: 'n-011',
    type: 'ORDER_ASSIGNED',
    title: 'Order Assigned',
    message: 'Order SH-x8k3n2m9 assigned to you.',
    orderRef: 'SH-x8k3n2m9',
    isRead: false,
    timestamp: 'Yesterday, 3:00 PM',
  },
  {
    id: 'n-012',
    type: 'SYSTEM_UPDATE',
    title: 'System Update',
    message: 'New driver Sarah Davies is now available and ready for assignments.',
    boldRef: 'Sarah Davies',
    isRead: true,
    timestamp: 'Yesterday, 11:00 AM',
  },
  {
    id: 'n-013',
    type: 'DELIVERY_COMPLETED',
    title: 'Delivery Completed',
    message: 'Package SH-4K22L9P was delivered with signature received.',
    orderRef: 'SH-4K22L9P',
    isRead: true,
    timestamp: 'Apr 7, 10:45 AM',
  },
  {
    id: 'n-014',
    type: 'DRIVER_ONLINE',
    title: 'New Driver Online',
    message: 'Driver Marcus Rivera is now online and available for assignments.',
    boldRef: 'Marcus Rivera',
    isRead: true,
    timestamp: 'Apr 7, 08:30 AM',
  },
  {
    id: 'n-015',
    type: 'DELIVERY_FAILED',
    title: 'Delivery Failed',
    message: 'Order SH-P5R1Q8Z3 failed: Incorrect address provided.',
    orderRef: 'SH-P5R1Q8Z3',
    errorRef: 'Incorrect address provided.',
    isRead: true,
    timestamp: 'Apr 6, 05:10 PM',
  },
  {
    id: 'n-016',
    type: 'SYSTEM_MAINTENANCE',
    title: 'System Maintenance',
    message: 'Planned maintenance window begins at 02:00 AM. Tracking may be temporarily unavailable.',
    isRead: true,
    timestamp: 'Apr 6, 01:00 PM',
  },
  {
    id: 'n-017',
    type: 'ORDER_ASSIGNED',
    title: 'Order Assigned',
    message: 'Order SH-R7T2M9X1 has been assigned to driver Priya Sharma.',
    orderRef: 'SH-R7T2M9X1',
    boldRef: 'Priya Sharma',
    isRead: true,
    timestamp: 'Apr 6, 10:00 AM',
  },
  {
    id: 'n-018',
    type: 'ROUTE_UPDATED',
    title: 'Route Updated',
    message: 'Route for SH-B3Q7N1Z8 adjusted due to road closure on Lekki Expressway.',
    orderRef: 'SH-B3Q7N1Z8',
    isRead: true,
    timestamp: 'Apr 5, 04:30 PM',
  },
  {
    id: 'n-019',
    type: 'DELIVERY_COMPLETED',
    title: 'Delivery Completed',
    message: 'Package SH-2N88M4Z delivered to recipient at Acme Corp HQ.',
    orderRef: 'SH-2N88M4Z',
    isRead: true,
    timestamp: 'Apr 5, 02:30 PM',
  },
  {
    id: 'n-020',
    type: 'SHIPMENT_UPDATE',
    title: 'Shipment Update',
    message: 'Bulk shipment SH-K9J2L5W4 departed from Victoria Island Hub.',
    orderRef: 'SH-K9J2L5W4',
    isRead: true,
    timestamp: 'Apr 5, 09:00 AM',
  },
  {
    id: 'n-021',
    type: 'ORDER_ASSIGNED',
    title: 'Order Assigned',
    message: 'Order SH-M2N9V4L1 has been assigned to driver Elena Walsh.',
    orderRef: 'SH-M2N9V4L1',
    boldRef: 'Elena Walsh',
    isRead: true,
    timestamp: 'Apr 4, 03:15 PM',
  },
  {
    id: 'n-022',
    type: 'DELIVERY_FAILED',
    title: 'Delivery Failed',
    message: 'Order SH-9W21P6K failed: Recipient refused delivery.',
    orderRef: 'SH-9W21P6K',
    errorRef: 'Recipient refused delivery.',
    isRead: true,
    timestamp: 'Apr 4, 01:00 PM',
  },
  {
    id: 'n-023',
    type: 'SYSTEM_UPDATE',
    title: 'System Update',
    message: 'Live tracking module updated to v2.4. New ETA calculation engine is active.',
    isRead: true,
    timestamp: 'Apr 3, 11:00 AM',
  },
  {
    id: 'n-024',
    type: 'DELIVERY_COMPLETED',
    title: 'Delivery Completed',
    message: 'Package SH-D2K7B3X9 delivered and signed at Ikoyi Estate.',
    orderRef: 'SH-D2K7B3X9',
    isRead: true,
    timestamp: 'Apr 3, 09:30 AM',
  },
];
