import type { TeamMember, UserRole, MemberStatus } from '@/types/settings';

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'usr-001',
    name: 'Alex Rivera',
    email: 'alex.rivera@swifthaul.com',
    role: 'ADMIN',
    status: 'ACTIVE',
    joinedDate: 'Jan 12, 2023',
    title: 'Head Dispatcher',
    avatarInitials: 'AR',
    isCurrentUser: true,
  },
  {
    id: 'usr-002',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@swifthaul.com',
    role: 'ADMIN',
    status: 'ACTIVE',
    joinedDate: 'Mar 05, 2023',
    title: 'Head of Operations',
    avatarInitials: 'SJ',
  },
  {
    id: 'usr-003',
    name: 'Marcus Thompson',
    email: 'marcus.thompson@swifthaul.com',
    role: 'DRIVER',
    status: 'ACTIVE',
    joinedDate: 'Jun 20, 2023',
    title: 'Senior Heavy Haul',
    avatarInitials: 'MT',
  },
  {
    id: 'usr-004',
    name: 'Elena Walsh',
    email: 'elena.walsh@swifthaul.com',
    role: 'DISPATCHER',
    status: 'ACTIVE',
    joinedDate: 'Aug 11, 2023',
    title: 'Operations Dispatcher',
    avatarInitials: 'EW',
  },
  {
    id: 'usr-005',
    name: 'David Lopez',
    email: 'david.lopez@swifthaul.com',
    role: 'DRIVER',
    status: 'ACTIVE',
    joinedDate: 'Oct 02, 2023',
    title: 'Express Delivery',
    avatarInitials: 'DL',
  },
  {
    id: 'usr-006',
    name: 'Priya Sharma',
    email: 'priya.sharma@swifthaul.com',
    role: 'DISPATCHER',
    status: 'ACTIVE',
    joinedDate: 'Nov 15, 2023',
    title: 'Fleet Coordinator',
    avatarInitials: 'PS',
  },
  {
    id: 'usr-007',
    name: 'James Okafor',
    email: 'james.okafor@swifthaul.com',
    role: 'DRIVER',
    status: 'INVITED',
    joinedDate: 'Jan 08, 2024',
    title: 'City Logistics',
    avatarInitials: 'JO',
  },
  {
    id: 'usr-008',
    name: 'Mia Chen',
    email: 'mia.chen@swifthaul.com',
    role: 'DRIVER',
    status: 'DEACTIVATED',
    joinedDate: 'Feb 20, 2024',
    title: 'Last-Mile Driver',
    avatarInitials: 'MC',
  },
  {
    id: 'usr-009',
    name: 'Andre Mitchell',
    email: 'andre.mitchell@swifthaul.com',
    role: 'DRIVER',
    status: 'ACTIVE',
    joinedDate: 'Mar 14, 2024',
    title: 'Route Specialist',
    avatarInitials: 'AM',
  },
  {
    id: 'usr-010',
    name: 'Fatima Hassan',
    email: 'fatima.hassan@swifthaul.com',
    role: 'DISPATCHER',
    status: 'ACTIVE',
    joinedDate: 'Apr 01, 2024',
    title: 'Senior Dispatcher',
    avatarInitials: 'FH',
  },
];

export const ROLE_STYLES: Record<UserRole, string> = {
  ADMIN:      'bg-primary-subtle text-primary-light',
  DISPATCHER: 'bg-info/10 text-info',
  DRIVER:     'bg-surface-elevated text-text-secondary border border-border',
};

export const STATUS_STYLES: Record<MemberStatus, { dot: string; text: string; label: string }> = {
  ACTIVE:      { dot: 'bg-success',      text: 'text-success',      label: 'ACTIVE' },
  INVITED:     { dot: 'bg-warning',      text: 'text-warning',      label: 'INVITED' },
  DEACTIVATED: { dot: 'bg-border-strong', text: 'text-text-muted',  label: 'DEACTIVATED' },
};
